### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kwyxz** [RobLoach/libretro-thumbnails-check#10]
Hello @RobLoach 

I am back to gathering boxarts for the libretro-thumbnails project, but am having issues building the latest version of your sweet check tool. Here's the output of `make` : 

```
kwyxz:libretro-thumbnails-check/ (master✗) $ make                                                      [23:07:33]
mkdir -p .tmp
git submodule init
git submodule update
mkdir -p out
npm install
npm WARN package.json libretro-thumbnails-check@0.0.1 No repository field.
\nter passphrase for key '/home/kwyxz/.ssh/id_rsa_kwyxz_4096b': |
npm ERR! git clone git@github.com:github:robloach/datfile Cloning into bare repository '/home/kwyxz/.npm/_git-remotes/git-github-com-github-robloach-datfile-f931c696'...
npm ERR! git clone git@github.com:github:robloach/datfile fatal: remote error: 
npm ERR! git clone git@github.com:github:robloach/datfile    is not a valid repository name
npm ERR! git clone git@github.com:github:robloach/datfile   Email support@github.com for help
npm ERR! notarget No compatible version found: robloach-datfile@'github:robloach/datfile#master'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.4.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.9.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/src/libretro-thumbnails-check
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/src/libretro-thumbnails-check/npm-debug.log
npm ERR! not ok code 0
Makefile:6: recipe for target 'node_modules' failed
make: *** [node_modules] Error 1
```
I attached the log file npm-debug.log after renaming it to .txt [npm-debug.log.txt](https://github.com/RobLoach/libretro-thumbnails-check/files/946127/npm-debug.log.txt) and hope it helps.

Thank you!

**Comment by RobLoach** [comment]
What version of node do you have installed? I've been using it on 4/6/7.

**Comment by kwyxz** [comment]
This is what I have (Debian Sid) 

```
kwyxz:libretro-thumbnails-check/ (master✗) $ nodejs --version                                                            [23:41:12]
v4.8.2
```
I installed the `nodejs` and `npm` packages (the latter came with a handful of dependencies)

**Comment by RobLoach** [comment]
Just made a release of the package so it doesn't use git. Mind doing a fresh git pull and another `npm i`?

**Comment by kwyxz** [comment]
No luck it seems

```
kwyxz:libretro-thumbnails-check/ (master✗) $ npm i                                                                       [23:46:28]
npm WARN package.json libretro-thumbnails-check@0.1.0 No repository field.
-
> sleep@5.1.1 install /usr/local/src/libretro-thumbnails-check/node_modules/sleep
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.9.0-2-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/src/libretro-thumbnails-check/node_modules/sleep
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! sleep@5.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.1.1 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.9.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /usr/local/src/libretro-thumbnails-check
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/src/libretro-thumbnails-check/npm-debug.log
npm ERR! not ok code 0
```
I even went as far as deleting everything, `git clone` again, `make clean && make`, looks like I am getting the same error.

**Comment by RobLoach** [comment]
Seems like https://www.npmjs.com/package/sleep is problematic. We'll need an alternative to that.

**Comment by kwyxz** [comment]
I noticed this in the output: `/bin/sh: 1: node: not found`
It reminded me of a similar issue I had in https://github.com/RobLoach/libretro-thumbnails-check/issues/5
I created a symbolic link from /usr/bin/node to /usr/bin/nodejs
It still crashes but not in the same location

```
kwyxz:libretro-thumbnails-check/ (master✗) $ make                                                                        [23:49:15]
mkdir -p .tmp
git submodule init
git submodule update
Submodule path 'libretro-database': checked out '9e962c2709927f1464b5a335794e24fa77e2111e'
mkdir -p out
npm install
npm WARN package.json libretro-thumbnails-check@0.1.0 No repository field.
npm WARN engine file-exists@3.0.2: wanted: {"node":">=6.0.0"} (current: {"node":"4.8.2","npm":"1.4.21"})
npm WARN engine rxjs@5.3.0: wanted: {"npm":">=2.0.0"} (current: {"node":"4.8.2","npm":"1.4.21"})
 
> sleep@5.1.1 install /usr/local/src/libretro-thumbnails-check/node_modules/sleep
> node-gyp rebuild

make[1]: Entering directory '/usr/local/src/libretro-thumbnails-check/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/obj.target/node_sleep.node
  COPY Release/node_sleep.node
make[1]: Leaving directory '/usr/local/src/libretro-thumbnails-check/node_modules/sleep/build'
download-file-sync@1.0.4 node_modules/download-file-sync

fs-exists-sync@0.1.0 node_modules/fs-exists-sync

batchreplace@1.0.1 node_modules/batchreplace

file-exists@3.0.2 node_modules/file-exists

recursive-readdir-sync@1.0.6 node_modules/recursive-readdir-sync

text-table@0.2.0 node_modules/text-table

marked@0.3.6 node_modules/marked

multimatch@2.1.0 node_modules/multimatch
├── array-differ@1.0.0
├── arrify@1.0.1
└── array-union@1.0.2 (array-uniq@1.0.3)

minimatch@3.0.3 node_modules/minimatch
└── brace-expansion@1.1.7 (balanced-match@0.4.2, concat-map@0.0.1)

robloach-datfile@1.1.0 node_modules/robloach-datfile
└── extend-shallow@2.0.1 (is-extendable@0.1.1)

glob@7.1.1 node_modules/glob
├── path-is-absolute@1.0.1
├── inherits@2.0.3
├── fs.realpath@1.0.0
├── inflight@1.0.6 (wrappy@1.0.2)
└── once@1.4.0 (wrappy@1.0.2)

globby@6.1.0 node_modules/globby
├── pify@2.3.0
├── object-assign@4.1.1
├── pinkie-promise@2.0.1 (pinkie@2.0.4)
└── array-union@1.0.2 (array-uniq@1.0.3)

sanitize-filename@1.6.1 node_modules/sanitize-filename
└── truncate-utf8-bytes@1.0.2 (utf8-byte-length@1.0.4)

sort-object@3.0.2 node_modules/sort-object
├── get-value@2.0.6
├── sort-desc@0.2.0
├── is-extendable@0.1.1
├── sort-asc@0.2.0
├── bytewise@1.1.0 (typewise@1.0.3, bytewise-core@1.2.3)
└── union-value@0.2.4 (arr-union@3.1.0, set-value@0.4.3)

multispinner@0.2.1 node_modules/multispinner
├── kind-of@2.0.1 (is-buffer@1.1.5)
├── figures@1.7.0 (object-assign@4.1.1, escape-string-regexp@1.0.5)
├── chalk@1.1.3 (ansi-styles@2.2.1, supports-color@2.0.0, escape-string-regexp@1.0.5, has-ansi@2.0.0, strip-ansi@3.0.1)
├── lodash.merge@3.3.2 (lodash.isarguments@3.1.0, lodash.istypedarray@3.0.6, lodash.isarray@3.0.4, lodash.keys@3.1.2, lodash._arraycopy@3.0.0, lodash.keysin@3.0.8, lodash._arrayeach@3.0.0, lodash._getnative@3.9.1, lodash.isplainobject@3.2.0, lodash._createassigner@3.1.1, lodash.toplainobject@3.0.0)
├── log-update@1.0.2 (ansi-escapes@1.4.0, cli-cursor@1.0.2)
└── lodash.clonedeep@3.0.2 (lodash._bindcallback@3.0.1, lodash._baseclone@3.3.0)

sleep@5.1.1 node_modules/sleep
└── nan@2.6.2

listr@0.11.0 node_modules/listr
├── listr-silent-renderer@1.1.1
├── log-symbols@1.0.2
├── is-stream@1.1.0
├── is-promise@2.1.0
├── stream-to-observable@0.1.0
├── strip-ansi@3.0.1 (ansi-regex@2.1.1)
├── figures@1.7.0 (escape-string-regexp@1.0.5, object-assign@4.1.1)
├── listr-update-renderer@0.2.0 (elegant-spinner@1.0.1, indent-string@3.1.0)
├── chalk@1.1.3 (supports-color@2.0.0, ansi-styles@2.2.1, escape-string-regexp@1.0.5, has-ansi@2.0.0)
├── indent-string@2.1.0 (repeating@2.0.1)
├── log-update@1.0.2 (ansi-escapes@1.4.0, cli-cursor@1.0.2)
├── cli-truncate@0.2.1 (slice-ansi@0.0.4, string-width@1.0.2)
├── ora@0.2.3 (cli-spinners@0.1.2, object-assign@4.1.1, cli-cursor@1.0.2)
├── listr-verbose-renderer@0.4.0 (cli-cursor@1.0.2, date-fns@1.28.3)
└── rxjs@5.3.0 (symbol-observable@1.0.4)
#@node --stack-size=1000000000 index.js
npm test

> libretro-thumbnails-check@0.1.0 test /usr/local/src/libretro-thumbnails-check
> bin/libretro-thumbnails-check.js

/usr/local/src/libretro-thumbnails-check/bin/libretro-thumbnails-check.js:20
		let system = path.parse(file).name
		^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 1
```

**Comment by RobLoach** [comment]
Just removed `sleep`.

**Comment by kwyxz** [comment]
Same crash unfortunately

```
kwyxz:libretro-thumbnails-check/ (master✗) $ make                                                                        [23:55:13]
mkdir -p .tmp
git submodule init
Submodule 'libretro-database' (git@github.com:libretro/libretro-database.git) registered for path 'libretro-database'
git submodule update
Cloning into '/usr/local/src/libretro-thumbnails-check/libretro-database'...
Enter passphrase for key '/home/kwyxz/.ssh/id_rsa_kwyxz_4096b': 
Submodule path 'libretro-database': checked out '9e962c2709927f1464b5a335794e24fa77e2111e'
mkdir -p out
npm install
npm WARN package.json libretro-thumbnails-check@0.2.0 No repository field.
npm WARN engine file-exists@3.0.2: wanted: {"node":">=6.0.0"} (current: {"node":"4.8.2","npm":"1.4.21"})
npm WARN engine rxjs@5.3.0: wanted: {"npm":">=2.0.0"} (current: {"node":"4.8.2","npm":"1.4.21"})
download-file-sync@1.0.4 node_modules/download-file-sync

fs-exists-sync@0.1.0 node_modules/fs-exists-sync

batchreplace@1.0.1 node_modules/batchreplace

file-exists@3.0.2 node_modules/file-exists

recursive-readdir-sync@1.0.6 node_modules/recursive-readdir-sync

text-table@0.2.0 node_modules/text-table

marked@0.3.6 node_modules/marked

globby@6.1.0 node_modules/globby
├── object-assign@4.1.1
├── pify@2.3.0
├── pinkie-promise@2.0.1 (pinkie@2.0.4)
└── array-union@1.0.2 (array-uniq@1.0.3)

robloach-datfile@1.1.0 node_modules/robloach-datfile
└── extend-shallow@2.0.1 (is-extendable@0.1.1)

minimatch@3.0.3 node_modules/minimatch
└── brace-expansion@1.1.7 (balanced-match@0.4.2, concat-map@0.0.1)

multimatch@2.1.0 node_modules/multimatch
├── array-differ@1.0.0
├── arrify@1.0.1
└── array-union@1.0.2 (array-uniq@1.0.3)

glob@7.1.1 node_modules/glob
├── path-is-absolute@1.0.1
├── inherits@2.0.3
├── fs.realpath@1.0.0
├── once@1.4.0 (wrappy@1.0.2)
└── inflight@1.0.6 (wrappy@1.0.2)

sanitize-filename@1.6.1 node_modules/sanitize-filename
└── truncate-utf8-bytes@1.0.2 (utf8-byte-length@1.0.4)

multispinner@0.2.1 node_modules/multispinner
├── figures@1.7.0 (escape-string-regexp@1.0.5, object-assign@4.1.1)
├── kind-of@2.0.1 (is-buffer@1.1.5)
├── chalk@1.1.3 (ansi-styles@2.2.1, supports-color@2.0.0, escape-string-regexp@1.0.5, strip-ansi@3.0.1, has-ansi@2.0.0)
├── lodash.merge@3.3.2 (lodash.isarguments@3.1.0, lodash.istypedarray@3.0.6, lodash._arraycopy@3.0.0, lodash._arrayeach@3.0.0, lodash._getnative@3.9.1, lodash.isarray@3.0.4, lodash.keys@3.1.2, lodash.keysin@3.0.8, lodash.toplainobject@3.0.0, lodash._createassigner@3.1.1, lodash.isplainobject@3.2.0)
├── lodash.clonedeep@3.0.2 (lodash._bindcallback@3.0.1, lodash._baseclone@3.3.0)
└── log-update@1.0.2 (ansi-escapes@1.4.0, cli-cursor@1.0.2)

sort-object@3.0.2 node_modules/sort-object
├── get-value@2.0.6
├── is-extendable@0.1.1
├── sort-desc@0.2.0
├── sort-asc@0.2.0
├── bytewise@1.1.0 (typewise@1.0.3, bytewise-core@1.2.3)
└── union-value@0.2.4 (arr-union@3.1.0, set-value@0.4.3)

listr@0.11.0 node_modules/listr
├── listr-silent-renderer@1.1.1
├── log-symbols@1.0.2
├── is-stream@1.1.0
├── is-promise@2.1.0
├── stream-to-observable@0.1.0
├── strip-ansi@3.0.1 (ansi-regex@2.1.1)
├── figures@1.7.0 (escape-string-regexp@1.0.5, object-assign@4.1.1)
├── log-update@1.0.2 (ansi-escapes@1.4.0, cli-cursor@1.0.2)
├── chalk@1.1.3 (supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, escape-string-regexp@1.0.5)
├── ora@0.2.3 (object-assign@4.1.1, cli-spinners@0.1.2, cli-cursor@1.0.2)
├── listr-update-renderer@0.2.0 (elegant-spinner@1.0.1, indent-string@3.1.0)
├── indent-string@2.1.0 (repeating@2.0.1)
├── listr-verbose-renderer@0.4.0 (cli-cursor@1.0.2, date-fns@1.28.3)
├── rxjs@5.3.0 (symbol-observable@1.0.4)
└── cli-truncate@0.2.1 (slice-ansi@0.0.4, string-width@1.0.2)
#@node --stack-size=1000000000 index.js
npm test

> libretro-thumbnails-check@0.2.0 test /usr/local/src/libretro-thumbnails-check
> bin/libretro-thumbnails-check.js

/usr/local/src/libretro-thumbnails-check/bin/libretro-thumbnails-check.js:20
		let system = path.parse(file).name
		^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 1
```

I have taken a look at `/usr/share/doc/nodejs/README.Debian` and it says the following:

```
nodejs command
--------------

The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".

This was done to prevent a namespace collision: other commands use
the same name in their upstreams, such as ax25-node from the "node"
package.

Scripts calling Node.js as a shell command must be changed to instead
use the "nodejs" command.
```

I'm starting to wonder if my symlink is actually helping or making things worse. Maybe I should simply edit the Makefile? Looking into that (I am super not familiar with nodejs so it's a shot in the dark)

EDIT: well after looking at the Makefile I doubt the issue is in there :D

**Comment by RobLoach** [comment]
Made some fixes.... Still an error with `file-exists` on Node < 6:
https://github.com/scottcorgan/file-exists/blob/master/index.js#L4

It'll now need at least Node.js 6, unless we replace file-exists. You may want to try out [nvm](https://github.com/creationix/nvm) as it'll install the latest version for you:
https://github.com/creationix/nvm

**Comment by kwyxz** [comment]
Ooooh so the issue comes from the version of Nodejs within Debian? That would explain a lot. Thanks for the tip, I'll try out nvm and will let you know.

**Comment by kwyxz** [comment]
Aaaaand that was it. I used this https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions to install NodeJS v7 and it worked like a charm... sorry for this inconvenience, I wonder what Debian is waiting for, lagging 3 versions behind is not great. Thanks again @RobLoach

**Comment by RobLoach** [comment]
> Ooooh so the issue comes from the version of Nodejs within Debian

Agreed, I've found Debian behind for a lot of development-related packages.
