### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kwyxz** [RobLoach/libretro-thumbnails-check#5]
Hello Rob,

I tried building the tool but unfortunately am quite stuck here:

```
kwyxz:libretro-thumbnails-check/ (master✗) $ make                             [14:00:38]
mkdir -p .tmp
git submodule init
git submodule update
mkdir -p out
npm install
npm WARN package.json libretro-thumbnails-check@0.0.1 No repository field.
npm ERR! git clone git@github.com:github:robloach/datfile Cloning into bare repository '/home/kwyxz/.npm/_git-remotes/git-github-com-github-robloach-datfile-f931c696'...
npm ERR! git clone git@github.com:github:robloach/datfile fatal: remote error: 
npm ERR! git clone git@github.com:github:robloach/datfile    is not a valid repository name
npm ERR! git clone git@github.com:github:robloach/datfile   Email support@github.com for help
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'datfile' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'libretro-thumbnails-check'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.8.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/src/libretro-thumbnails-check
npm ERR! node -v v4.6.1
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/src/libretro-thumbnails-check/npm-debug.log
npm ERR! not ok code 0
Makefile:5: recipe for target 'node_modules' failed
make: *** [node_modules] Error 1
```

Attached is the detailed log file.

Thank you for your help!

[npm-debug.log.txt](https://github.com/RobLoach/libretro-thumbnails-check/files/644831/npm-debug.log.txt)

**Comment by RobLoach** [comment]
Fixed :+1: 

Mind trying again? Switched to use `robloach-datfile` just to publish it on npm.

**Comment by kwyxz** [comment]
Thanks!

It goes a bit further now

```
kwyxz:libretro-thumbnails-check/ (master) $ make clean                                                                                                                                       [19:04:38]
rm -rf .tmp out node_modules
kwyxz:libretro-thumbnails-check/ (master✗) $ make                                                                                                                                            [19:04:39]
mkdir -p .tmp
git submodule init
Submodule 'libretro-database' (git@github.com:libretro/libretro-database.git) registered for path 'libretro-database'
git submodule update
Cloning into '/usr/local/src/libretro-thumbnails-check/libretro-database'...
Enter passphrase for key '/home/kwyxz/.ssh/id_rsa': 
Submodule path 'libretro-database': checked out '639008b053e599f5052c156bf4c8ea5ec22a7a36'
mkdir -p out
npm install
npm WARN package.json libretro-thumbnails-check@0.0.1 No repository field.
 
> sleep@5.0.0 install /usr/local/src/libretro-thumbnails-check/node_modules/sleep
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-2-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/src/libretro-thumbnails-check/node_modules/sleep
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! sleep@5.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.0.0 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.8.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/src/libretro-thumbnails-check
npm ERR! node -v v4.6.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/src/libretro-thumbnails-check/npm-debug.log
npm ERR! not ok code 0
Makefile:5: recipe for target 'node_modules' failed
make: *** [node_modules] Error 1
```

Sadly I am super not familiar with node.js, could it be a package is missing on my system? I have no "node" executable even though nodejs is installed. I'm running Debian Sid.

```
kwyxz:libretro-thumbnails-check/ (master✗) $ dpkg -l | grep node                                                                                                                             [19:08:52]
ii  libjs-node-uuid                       1.4.0-1                              all          simple, fast generation of RFC4122 UUIDs - JavaScript library
ii  node-abbrev                           1.0.9-1                              all          Get unique abbreviations for a set of strings - Node.js module
ii  node-ansi                             0.3.0-2                              all          Advanced ANSI formatting tool for Node.js
ii  node-ansi-color-table                 1.0.0-1                              all          Color and format tables for ansi output - Node.js module
ii  node-archy                            0.0.2-1                              all          Pretty-print nested hierarchies module for Node.js
ii  node-async                            0.8.0-1                              all          higher-order functions and common patterns for asynchronous Javascript
ii  node-balanced-match                   0.4.2-1                              all          Match balanced character pairs in Node.js
ii  node-block-stream                     0.0.9-1                              all          Stream of fixed-size blocks, with zero-padding when necessary
ii  node-brace-expansion                  1.1.6-1                              all          Brace expansion as known from sh/bash for Node.js
ii  node-builtin-modules                  1.1.1-1                              all          List of the Node.js builtin modules
ii  node-combined-stream                  0.0.5-1                              all          Append streams one after another - module for Node.js
ii  node-concat-map                       0.0.1-1                              all          concatenative mapdashery for Node.js
ii  node-cookie-jar                       0.3.1-1                              all          Cookie handling for HTTP clients - module for Node.js
ii  node-delayed-stream                   0.0.5-1                              all          Buffer stream events for later handling - module for Node.js
ii  node-forever-agent                    0.5.1-1                              all          HTTP agent supporting keep-alive requests - module for Node.js
ii  node-form-data                        0.1.0-1                              all          Create multipart/form-data streams module for Node.js
ii  node-fs.realpath                      1.0.0-1                              all          Use node's fs.realpath
ii  node-fstream                          1.0.10-1                             all          Advanced filesystem streaming tools for Node.js
ii  node-fstream-ignore                   0.0.6-2                              all          Directory reader configurable by .ignore module for Node.js
ii  node-github-url-from-git              1.4.0-1                              all          Convert github git or gist url to an http url - Node.js module
ii  node-glob                             7.1.1-1                              all          glob functionality for Node.js
ii  node-graceful-fs                      4.1.11-1                             all          drop-in replacement improving the Node.js fs module
ii  node-gyp                              3.4.0-1                              all          Native addon build tool for Node.js
ii  node-hosted-git-info                  2.1.5-1                              all          Provides metadata from Github, Bitbucket and Gitlab
ii  node-inflight                         1.0.6-1                              all          add callbacks to requests in flight to avoid async duplication
ii  node-inherits                         2.0.3-1                              all          Exposes inherits function from Node.js environment
ii  node-ini                              1.1.0-1                              all          ini format parser and serializer for Node.js
ii  node-is-builtin-module                1.0.0-1                              all          Check if string matches name of a Node.js builtin module
ii  node-isexe                            1.1.2-1                              all          minimal module to check if a file is executable
ii  node-json-stringify-safe              5.0.0-1                              all          JSON.stringify with circular references module for Node.js
ii  node-lockfile                         0.4.1-1                              all          Asynchronous file lock module for Node.js
ii  node-lru-cache                        4.0.2-1                              all          least-recently-used cache object for Node.js
ii  node-mime                             1.3.4-1                              all          library for mime-type mapping for Node.js
ii  node-minimatch                        3.0.3-1                              all          Convert glob expressions into RegExp objects for Node.js
ii  node-mkdirp                           0.5.0-1                              all          Recursively create directories - Node.js module
ii  node-mute-stream                      0.0.4-1                              all          Pass-through stream that can be muted module for Node.js
ii  node-node-uuid                        1.4.0-1                              all          simple, fast generation of RFC4122 UUIDs - Node module
ii  node-nopt                             3.0.6-3                              all          Command-line option parser for Node.js
ii  node-normalize-package-data           2.3.5-1                              all          Normalizes package metadata - Node.js module
ii  node-npmlog                           0.0.4-1                              all          Logger with custom levels and colored output for Node.js
ii  node-once                             1.4.0-2                              all          Run a function only once with this module for Node.js
ii  node-osenv                            0.1.0-1                              all          Environment settings lookup module for Node.js
ii  node-path-is-absolute                 1.0.0-1                              all          Node.js 0.12 path.isAbsolute() ponyfill
ii  node-pseudomap                        1.0.2-1                              all          like ES6 `Map`, but without iterators
ii  node-qs                               2.2.4-1                              all          Parse, stringify query strings for Node.js
ii  node-read                             1.0.5-1                              all          Read user input from stdin module for Node.js
ii  node-read-package-json                1.2.4-1                              all          Read package.json for npm module for Node.js
ii  node-request                          2.26.1-1                             all          simplified HTTP request client module for Node.js
ii  node-retry                            0.6.0-1                              all          Retry strategies for failed operations module for Node.js
ii  node-rimraf                           2.5.4-2                              all          Deep deletion (like rm -rf) module for Node.js
ii  node-semver                           5.3.0-1                              all          Semantic Versioning for Node.js
ii  node-sha                              1.2.3-1                              all          Check and get file or stream hashes - module for Node.js
ii  node-slide                            1.1.4-1                              all          Simple chain and asyncMap flow control module for Node.js
ii  node-spdx-correct                     1.0.2-1                              all          correct invalid SPDX identifiers
ii  node-spdx-expression-parse            1.0.4-1                              all          parse SPDX license expressions
ii  node-spdx-license-ids                 1.2.2-1                              all          List of SPDX license identifiers
ii  node-tar                              2.2.1-1                              all          read and write portable tar archives module for Node.js
ii  node-tunnel-agent                     0.3.1-1                              all          HTTP proxy tunneling agent module for Node.js
ii  node-underscore                       1.8.3~dfsg-1                         all          JavaScript's functional programming helper library - NodeJS
ii  node-validate-npm-package-license     3.0.1-1                              all          Tells if a string is a valid npm package license string
ii  node-which                            1.2.11-1                             all          Cross-platform 'which' module for Node.js
ii  node-wrappy                           1.0.2-1                              all          Callback wrapping utility
ii  node-yallist                          2.0.0-1                              all          Yet Another Linked List
ii  nodejs                                4.6.1~dfsg-1                         amd64        evented I/O for V8 javascript
ii  nodejs-dev                            4.6.1~dfsg-1                         amd64        evented I/O for V8 javascript (development files)
```

Thank you!

**Comment by kwyxz** [comment]
I think I made some progress. It seems like in Debian the executable is called `nodejs` and not `node` so I just created a symlink. Here's where I am now :

```
kwyxz:libretro-thumbnails-check/ (master✗) $ make                                                                                                                                            [19:17:52]
mkdir -p .tmp
git submodule init
git submodule update
mkdir -p out
npm install
npm WARN package.json libretro-thumbnails-check@0.0.1 No repository field.
 
> sleep@5.0.0 install /usr/local/src/libretro-thumbnails-check/node_modules/sleep
> node-gyp rebuild

make[1]: Entering directory '/usr/local/src/libretro-thumbnails-check/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/obj.target/node_sleep.node
  COPY Release/node_sleep.node
make[1]: Leaving directory '/usr/local/src/libretro-thumbnails-check/node_modules/sleep/build'
download-file-sync@1.0.4 node_modules/download-file-sync

batchreplace@1.0.1 node_modules/batchreplace

file-exists@2.0.0 node_modules/file-exists

text-table@0.2.0 node_modules/text-table

marked@0.3.6 node_modules/marked

multimatch@2.1.0 node_modules/multimatch
├── array-differ@1.0.0
├── arrify@1.0.1
└── array-union@1.0.2 (array-uniq@1.0.3)

minimatch@3.0.3 node_modules/minimatch
└── brace-expansion@1.1.6 (balanced-match@0.4.2, concat-map@0.0.1)

globby@6.1.0 node_modules/globby
├── object-assign@4.1.0
├── pify@2.3.0
├── pinkie-promise@2.0.1 (pinkie@2.0.4)
└── array-union@1.0.2 (array-uniq@1.0.3)

sanitize-filename@1.6.1 node_modules/sanitize-filename
└── truncate-utf8-bytes@1.0.2 (utf8-byte-length@1.0.4)

glob@7.1.1 node_modules/glob
├── path-is-absolute@1.0.1
├── inherits@2.0.3
├── fs.realpath@1.0.0
├── once@1.4.0 (wrappy@1.0.2)
└── inflight@1.0.6 (wrappy@1.0.2)

robloach-datfile@0.4.0 node_modules/robloach-datfile
├── convert-newline@0.0.5 (iconv-lite@0.4.15)
└── simple-text-parser@1.0.0 (lodash@3.10.1)

sleep@5.0.0 node_modules/sleep
└── nan@2.4.0
module.js:327
    throw err;
    ^

Error: Cannot find module 'datfile'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/src/libretro-thumbnails-check/index.js:6:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 1
```

**Comment by RobLoach** [comment]
Debian's package must be quite old. Hopefully they'll fix that up. In the mean time, a `git pull` should fix that module not found error you got.

Thanks for putting so much time into this! It's helped a lot.

One think you'll run into is the github access token. I'll add some more docs about that in the README.md

**Comment by kwyxz** [comment]
It seems to be working now! I think the issue was coming from my token being set on line 30 instead of line 31 (the comments confused me)

Anyway if you get errors from Debian / Ubuntu users, you can let them know that a symlink from /usr/bin/nodejs does the trick now :D

Thanks for your help!

**Comment by RobLoach** [comment]
Nicely done on your last update. Re-ran the thumbnails-check:
https://github.com/RobLoach/libretro-thumbnails-check/tree/master/out

**Comment by kwyxz** [comment]
Hi Rob, I've been running the check since my last update and there's something weird. In the Orphans file for the Super Nintendo, I can see the following:

```
Named_Boxarts/Acrobat Mission (Japan).png
Named_Boxarts/Andre Agassi Tennis (Japan).png
Named_Boxarts/Arkanoid - Doh It Again (Japan).png
```

However, all of these are available in the archive :

https://github.com/libretro/libretro-thumbnails/blob/master/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/Named_Boxarts/Acrobat%20Mission%20(Japan).png
https://github.com/libretro/libretro-thumbnails/blob/master/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/Named_Boxarts/Andre%20Agassi%20Tennis%20(Japan).png
https://github.com/libretro/libretro-thumbnails/blob/master/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/Named_Boxarts/Arkanoid%20-%20Doh%20It%20Again%20(Japan).png

Now looking at the No-Intro dat file... I can't find them. I am guessing some of them were renamed - the (Japan) ones seem to have become (Japan) (En). Is the libretro policy to follow strictly the No-Intro dats? If so, are we supposed to delete the extra arts? If you're not the best person to ask, who should I bother with this? :)

Thanks!

**Comment by RobLoach** [comment]
Yeah, the orphans indicate either a rename, or a file we don't need.

**Comment by kwyxz** [comment]
Alright then, I guess some cleanup will be in order. I'll take care of it sometime later.

**Comment by kwyxz** [comment]
I actually have another question, sorry :( 

This one appears in the Orphans :
`Named_Boxarts/Adventures of Batman & Robin, The (Europe).png`

It, however, is present in the DAT :
```
	name "Adventures of Batman & Robin, The (Europe)"
	description "Adventures of Batman & Robin, The (Europe)"
	rom ( name "Adventures of Batman & Robin, The (Europe).sfc" size 2097152 crc 96B0C568 md5 49775F5E46BE05C1E245B26A70B6F756 sha1 4D5AFC2D11B141DDC33753B6FB84847D2F2261BA )
```
And a boxart is present for it:
https://github.com/libretro/libretro-thumbnails/blob/master/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/Named_Boxarts/Adventures%20of%20Batman%20_%20Robin%2C%20The%20(Europe).png

Any idea why it's showing up as an orphan? Thanks!

**Comment by RobLoach** [comment]
`&` should be switched to `_`.... Would be nice to add to the orphan list suggesting fixes.

So it should be....
```
Named_Boxarts/Adventures of Batman _ Robin, The (Europe).png
```

**Comment by kwyxz** [comment]
Just to make sure I understand properly, the issue lies with the check script then, doesn't it? As the file name follows the RetroArch guidelines for renaming of special characters introduced here https://github.com/libretro/RetroArch/commit/5be99842b5f664ed1274c0b6918712bdac4241c5

**Comment by RobLoach** [comment]
Possibly, might need an update. Do a `make clean`, and it should clear out the tmp cache.

**Comment by kwyxz** [comment]
I think we're good now. You can close this bug!

```
Nintendo - Super Nintendo Entertainment System
Boxarts   3327/3438  96.77%
```

It's mostly cleanup at this point.

**Comment by RobLoach** [comment]
So close to hit 100!
